name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
      
      - name: Prepare APK
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          find ${{ github.workspace }}/app/build/outputs/apk/ -name "*.apk" -exec mv {} ${{ github.workspace }}/apk/ \;
      
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*
